services:
  backend:
    ports:
      - "127.0.0.1:${JUNJO_LOCAL_PROD_BACKEND_PORT:-8081}:1323"
    environment:
      JUNJO_DEV_FRONTEND_PORT: ${JUNJO_LOCAL_PROD_FRONTEND_PORT:-8080}
      JUNJO_DEV_BACKEND_PORT: ${JUNJO_LOCAL_PROD_BACKEND_PORT:-8081}
      JUNJO_DEV_OTLP_GRPC_PORT: ${JUNJO_LOCAL_PROD_OTLP_GRPC_PORT:-4317}

  ingestion:
    ports:
      - "127.0.0.1:${JUNJO_LOCAL_PROD_OTLP_GRPC_PORT:-4317}:4317"

  frontend:
    ports:
      - "127.0.0.1:${JUNJO_LOCAL_PROD_FRONTEND_PORT:-8080}:80"
    environment:
      JUNJO_DEV_FRONTEND_PORT: ${JUNJO_LOCAL_PROD_FRONTEND_PORT:-8080}
      JUNJO_DEV_BACKEND_PORT: ${JUNJO_LOCAL_PROD_BACKEND_PORT:-8081}
      JUNJO_DEV_OTLP_GRPC_PORT: ${JUNJO_LOCAL_PROD_OTLP_GRPC_PORT:-4317}
