services:
  junjo-server-backend:
    container_name: junjo-server-backend
    restart: unless-stopped
    build:
      context: ./backend
      target: ${JUNJO_BUILD_TARGET:-production} # Default to 'production', set to "development" for local air hot-reloading
    volumes:
      - ./backend:/app # Mount the backend code for hot reloading
      - ./.dbdata/sqlite:/dbdata/sqlite # SQLite storage
      - ./.dbdata/duckdb:/dbdata/duckdb # DuckDB storage
    ports:
      - "1323:1323" # Public API server port for Junjo UX
      - "50053:50053" # Internal gRPC server port
    networks:
      - junjo-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1323/ping"]
      interval: 5s
      timeout: 3s
      retries: 25
      start_period: 5s

  ingestion-service:
    container_name: ingestion-service
    restart: unless-stopped
    build:
      context: ./ingestion-service
      target: ${JUNJO_BUILD_TARGET:-production}
    volumes:
      - ./ingestion-service:/app
      - ./.dbdata/badgerdb:/dbdata/badgerdb # BadgerDB storage
    ports:
      - "50051:50051" # Public gRPC telemetry server port for Junjo SDK Otel Exporter
      - "50052:50052" # Internal gRPC server port
    networks:
      - junjo-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50052"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  junjo-server-frontend:
    container_name: junjo-server-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      target: ${JUNJO_BUILD_TARGET:-production} # Default to 'production', set to "development" for local air hot-reloading
    volumes:
      - frontend-modules:/app/node_modules # Dev only: Named volume for node_modules
      - ./frontend:/app # Dev only: Mount the frontend code for hot reloading
    ports:
      # Development ports (Vite)
      - "5151:5151" # Vite server
      - "5152:5151" # Vite hmr (map hmr port to host port)
      - "5153:80" # Production port to web server mapping
    env_file:
      - .env
    depends_on:
      junjo-server-backend:
        condition: service_healthy # Wait for junjo-server-backend to be healthy before starting junjo-server-frontend
      ingestion-service:
        condition: service_healthy

volumes:
  frontend-modules: # Dev only: Named volume for node_modules

networks:
  junjo-network:
    driver: bridge
