services:
  junjo-server-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "1323:1323"
    environment:
      - DEBUG=true
      - APP_NAME=Junjo Server
      - DB_SQLITE_PATH=/dbdata/sqlite/junjo.db
      - DB_DUCKDB_PATH=/dbdata/duckdb/traces.duckdb
      - INGESTION_HOST=junjo-server-ingestion
      - INGESTION_PORT=50052
      - CORS_ORIGINS=["http://localhost:5151"]
      - RUN_MIGRATIONS=true
    volumes:
      - ./.dbdata:/dbdata
      - ./backend/app:/app/app
    networks:
      - junjo-network

  junjo-server-ingestion:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "50052:50052"
    environment:
      - BADGERDB_PATH=/dbdata/badgerdb
      - BACKEND_GRPC_HOST=junjo-server-backend
      - BACKEND_GRPC_PORT=50053
    volumes:
      - ./.dbdata/badgerdb:/dbdata/badgerdb
    depends_on:
      - junjo-server-backend
    networks:
      - junjo-network

  junjo-server-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5151:80"
    environment:
      - VITE_API_URL=http://localhost:1323
    networks:
      - junjo-network

networks:
  junjo-network:
    driver: bridge
