// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/auth.proto

package proto_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_GetToken_FullMethodName = "/ingestion.AuthService/GetToken"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService provides a public endpoint for clients to exchange an API key
// for a short-lived JWT. This is the single point of contact for auth.
type AuthServiceClient interface {
	// GetToken exchanges a Junjo API Key for a JWT.
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService provides a public endpoint for clients to exchange an API key
// for a short-lived JWT. This is the single point of contact for auth.
type AuthServiceServer interface {
	// GetToken exchanges a Junjo API Key for a JWT.
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestion.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _AuthService_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}

const (
	InternalAuthService_ExchangeApiKeyForJwt_FullMethodName = "/ingestion.InternalAuthService/ExchangeApiKeyForJwt"
)

// InternalAuthServiceClient is the client API for InternalAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalAuthService provides a private API for the ingestion-service to
// validate API keys and receive signed JWTs from the backend.
type InternalAuthServiceClient interface {
	// ExchangeApiKeyForJwt validates an API key and returns a signed JWT.
	ExchangeApiKeyForJwt(ctx context.Context, in *ExchangeApiKeyForJwtRequest, opts ...grpc.CallOption) (*ExchangeApiKeyForJwtResponse, error)
}

type internalAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalAuthServiceClient(cc grpc.ClientConnInterface) InternalAuthServiceClient {
	return &internalAuthServiceClient{cc}
}

func (c *internalAuthServiceClient) ExchangeApiKeyForJwt(ctx context.Context, in *ExchangeApiKeyForJwtRequest, opts ...grpc.CallOption) (*ExchangeApiKeyForJwtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeApiKeyForJwtResponse)
	err := c.cc.Invoke(ctx, InternalAuthService_ExchangeApiKeyForJwt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalAuthServiceServer is the server API for InternalAuthService service.
// All implementations must embed UnimplementedInternalAuthServiceServer
// for forward compatibility.
//
// InternalAuthService provides a private API for the ingestion-service to
// validate API keys and receive signed JWTs from the backend.
type InternalAuthServiceServer interface {
	// ExchangeApiKeyForJwt validates an API key and returns a signed JWT.
	ExchangeApiKeyForJwt(context.Context, *ExchangeApiKeyForJwtRequest) (*ExchangeApiKeyForJwtResponse, error)
	mustEmbedUnimplementedInternalAuthServiceServer()
}

// UnimplementedInternalAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalAuthServiceServer struct{}

func (UnimplementedInternalAuthServiceServer) ExchangeApiKeyForJwt(context.Context, *ExchangeApiKeyForJwtRequest) (*ExchangeApiKeyForJwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeApiKeyForJwt not implemented")
}
func (UnimplementedInternalAuthServiceServer) mustEmbedUnimplementedInternalAuthServiceServer() {}
func (UnimplementedInternalAuthServiceServer) testEmbeddedByValue()                             {}

// UnsafeInternalAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalAuthServiceServer will
// result in compilation errors.
type UnsafeInternalAuthServiceServer interface {
	mustEmbedUnimplementedInternalAuthServiceServer()
}

func RegisterInternalAuthServiceServer(s grpc.ServiceRegistrar, srv InternalAuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalAuthService_ServiceDesc, srv)
}

func _InternalAuthService_ExchangeApiKeyForJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeApiKeyForJwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAuthServiceServer).ExchangeApiKeyForJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAuthService_ExchangeApiKeyForJwt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAuthServiceServer).ExchangeApiKeyForJwt(ctx, req.(*ExchangeApiKeyForJwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalAuthService_ServiceDesc is the grpc.ServiceDesc for InternalAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestion.InternalAuthService",
	HandlerType: (*InternalAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeApiKeyForJwt",
			Handler:    _InternalAuthService_ExchangeApiKeyForJwt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
