// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/ingestion.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadSpansRequest defines the parameters for requesting a batch of spans.
type ReadSpansRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ULID of the last span successfully processed by the client.
	// The server will return spans that were received *after* this key.
	// If empty, the stream will start from the oldest available span.
	StartKeyUlid []byte `protobuf:"bytes,1,opt,name=start_key_ulid,json=startKeyUlid,proto3" json:"start_key_ulid,omitempty"`
	// The maximum number of spans to return in the batch.
	BatchSize     uint32 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSpansRequest) Reset() {
	*x = ReadSpansRequest{}
	mi := &file_proto_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSpansRequest) ProtoMessage() {}

func (x *ReadSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSpansRequest.ProtoReflect.Descriptor instead.
func (*ReadSpansRequest) Descriptor() ([]byte, []int) {
	return file_proto_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *ReadSpansRequest) GetStartKeyUlid() []byte {
	if x != nil {
		return x.StartKeyUlid
	}
	return nil
}

func (x *ReadSpansRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

// ReadSpansResponse contains a single span from the WAL.
type ReadSpansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ULID key of the span, which also serves as its timestamp.
	KeyUlid []byte `protobuf:"bytes,1,opt,name=key_ulid,json=keyUlid,proto3" json:"key_ulid,omitempty"`
	// The raw, serialized protobuf bytes of the OTel span.
	SpanBytes []byte `protobuf:"bytes,2,opt,name=span_bytes,json=spanBytes,proto3" json:"span_bytes,omitempty"`
	// The raw, serialized protobuf bytes of the OTel resource.
	ResourceBytes []byte `protobuf:"bytes,3,opt,name=resource_bytes,json=resourceBytes,proto3" json:"resource_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSpansResponse) Reset() {
	*x = ReadSpansResponse{}
	mi := &file_proto_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSpansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSpansResponse) ProtoMessage() {}

func (x *ReadSpansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSpansResponse.ProtoReflect.Descriptor instead.
func (*ReadSpansResponse) Descriptor() ([]byte, []int) {
	return file_proto_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *ReadSpansResponse) GetKeyUlid() []byte {
	if x != nil {
		return x.KeyUlid
	}
	return nil
}

func (x *ReadSpansResponse) GetSpanBytes() []byte {
	if x != nil {
		return x.SpanBytes
	}
	return nil
}

func (x *ReadSpansResponse) GetResourceBytes() []byte {
	if x != nil {
		return x.ResourceBytes
	}
	return nil
}

var File_proto_ingestion_proto protoreflect.FileDescriptor

var file_proto_ingestion_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x57, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x75, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x55, 0x6c, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x74, 0x0a, 0x11, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x75, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x55, 0x6c, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x70, 0x61, 0x6e, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x32, 0x66, 0x0a, 0x18, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a,
	0x09, 0x52, 0x65, 0x61, 0x64, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x69, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x70, 0x61, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_ingestion_proto_rawDescOnce sync.Once
	file_proto_ingestion_proto_rawDescData []byte
)

func file_proto_ingestion_proto_rawDescGZIP() []byte {
	file_proto_ingestion_proto_rawDescOnce.Do(func() {
		file_proto_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ingestion_proto_rawDesc), len(file_proto_ingestion_proto_rawDesc)))
	})
	return file_proto_ingestion_proto_rawDescData
}

var file_proto_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ingestion_proto_goTypes = []any{
	(*ReadSpansRequest)(nil),  // 0: ingestion.ReadSpansRequest
	(*ReadSpansResponse)(nil), // 1: ingestion.ReadSpansResponse
}
var file_proto_ingestion_proto_depIdxs = []int32{
	0, // 0: ingestion.InternalIngestionService.ReadSpans:input_type -> ingestion.ReadSpansRequest
	1, // 1: ingestion.InternalIngestionService.ReadSpans:output_type -> ingestion.ReadSpansResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ingestion_proto_init() }
func file_proto_ingestion_proto_init() {
	if File_proto_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ingestion_proto_rawDesc), len(file_proto_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ingestion_proto_goTypes,
		DependencyIndexes: file_proto_ingestion_proto_depIdxs,
		MessageInfos:      file_proto_ingestion_proto_msgTypes,
	}.Build()
	File_proto_ingestion_proto = out.File
	file_proto_ingestion_proto_goTypes = nil
	file_proto_ingestion_proto_depIdxs = nil
}
