// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/span_data_container.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SpanDataContainer is a wrapper for storing a span and its resource together.
type SpanDataContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpanBytes     []byte                 `protobuf:"bytes,1,opt,name=span_bytes,json=spanBytes,proto3" json:"span_bytes,omitempty"`
	ResourceBytes []byte                 `protobuf:"bytes,2,opt,name=resource_bytes,json=resourceBytes,proto3" json:"resource_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanDataContainer) Reset() {
	*x = SpanDataContainer{}
	mi := &file_proto_span_data_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanDataContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanDataContainer) ProtoMessage() {}

func (x *SpanDataContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_span_data_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanDataContainer.ProtoReflect.Descriptor instead.
func (*SpanDataContainer) Descriptor() ([]byte, []int) {
	return file_proto_span_data_container_proto_rawDescGZIP(), []int{0}
}

func (x *SpanDataContainer) GetSpanBytes() []byte {
	if x != nil {
		return x.SpanBytes
	}
	return nil
}

func (x *SpanDataContainer) GetResourceBytes() []byte {
	if x != nil {
		return x.ResourceBytes
	}
	return nil
}

var File_proto_span_data_container_proto protoreflect.FileDescriptor

var file_proto_span_data_container_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x61, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x73, 0x70, 0x61, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x59, 0x0a, 0x11, 0x53, 0x70, 0x61, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x70, 0x61, 0x6e, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_span_data_container_proto_rawDescOnce sync.Once
	file_proto_span_data_container_proto_rawDescData []byte
)

func file_proto_span_data_container_proto_rawDescGZIP() []byte {
	file_proto_span_data_container_proto_rawDescOnce.Do(func() {
		file_proto_span_data_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_span_data_container_proto_rawDesc), len(file_proto_span_data_container_proto_rawDesc)))
	})
	return file_proto_span_data_container_proto_rawDescData
}

var file_proto_span_data_container_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_span_data_container_proto_goTypes = []any{
	(*SpanDataContainer)(nil), // 0: span_data_container.SpanDataContainer
}
var file_proto_span_data_container_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_span_data_container_proto_init() }
func file_proto_span_data_container_proto_init() {
	if File_proto_span_data_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_span_data_container_proto_rawDesc), len(file_proto_span_data_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_span_data_container_proto_goTypes,
		DependencyIndexes: file_proto_span_data_container_proto_depIdxs,
		MessageInfos:      file_proto_span_data_container_proto_msgTypes,
	}.Build()
	File_proto_span_data_container_proto = out.File
	file_proto_span_data_container_proto_goTypes = nil
	file_proto_span_data_container_proto_depIdxs = nil
}
