// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db_gen

import (
	"database/sql"
)

type Workflow struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
